// Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Johnny.Chen"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/login": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "user login",
                "parameters": [
                    {
                        "description": "user data",
                        "name": "userdata",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/GinProject_internal_model.LoginUserData"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "return jwt token",
                        "schema": {
                            "$ref": "#/definitions/GinProject_internal_model.LoginSuccessResponse"
                        }
                    }
                }
            }
        },
        "/user": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "get user list",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "page for pagination",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page size for pagination",
                        "name": "pagesize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "find user with fullname",
                        "name": "fullname",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "sort result by column",
                        "name": "sortby",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "return user list",
                        "schema": {
                            "$ref": "#/definitions/GinProject_internal_model.SuccessUserListResponse"
                        }
                    }
                }
            },
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "create user",
                "parameters": [
                    {
                        "description": "user data",
                        "name": "userdata",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/GinProject_internal_model.CreateUserData"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "return error message",
                        "schema": {
                            "$ref": "#/definitions/GinProject_internal_model.BasicSuccessResponse"
                        }
                    }
                }
            }
        },
        "/user/{account}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "get user",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "page for pagination",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page size for pagination",
                        "name": "pagesize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "find user with fullname",
                        "name": "fullname",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "sort result by column",
                        "name": "sortby",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "return user",
                        "schema": {
                            "$ref": "#/definitions/GinProject_internal_model.SuccessUserResponse"
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "delete user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user account",
                        "name": "account",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "return error message ",
                        "schema": {
                            "$ref": "#/definitions/GinProject_internal_model.BasicSuccessResponse"
                        }
                    }
                }
            },
            "patch": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "update user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user account",
                        "name": "account",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "user data",
                        "name": "userdata",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/GinProject_internal_model.UpdateUserData"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "return error message ",
                        "schema": {
                            "$ref": "#/definitions/GinProject_internal_model.BasicSuccessResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "GinProject_internal_model.ApiUsers": {
            "type": "object",
            "properties": {
                "account": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "fullname": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "GinProject_internal_model.BasicSuccessResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "GinProject_internal_model.CreateUserData": {
            "type": "object",
            "properties": {
                "account": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 4
                },
                "fullname": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 4
                },
                "password": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 8
                }
            }
        },
        "GinProject_internal_model.LoginSuccessResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "GinProject_internal_model.LoginUserData": {
            "type": "object",
            "properties": {
                "account": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 4
                },
                "password": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 8
                }
            }
        },
        "GinProject_internal_model.SuccessUserListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/GinProject_internal_model.ApiUsers"
                    }
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "GinProject_internal_model.SuccessUserResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/GinProject_internal_model.ApiUsers"
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "GinProject_internal_model.UpdateUserData": {
            "type": "object",
            "properties": {
                "fullname": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 4
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "GinProject",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
